### PR TITLE
Add tests to isSecretAddress function

### PR DESCRIPTION
**Pull request by Tosch110**
Add dedicated isSecretAddress with tests to check if the recipient is a valid secret address.

### CODE REVIEW

**Comment by Tosch110** [comment]
If you want I can remove the package-lock.json file - but actually it is recommended to have in the repository so I will delete on request.

**Comment by levackt** [comment]
Thanks @Tosch110 , but were you able to get invalid data into the contract via this UI? 

Prefix is configurable, so it would be nice to still be able to test the dapp on testnets like kamut, though not strictly required if this is a bug you can reproduce with any of that invalid data.

**Comment by Tosch110** [comment]
I understand, will have a look to make the prefix configurable 👍 

I have not done integration tests and will have a look at the invalid data in previous version aswell 👍

**Comment by Tosch110** [comment]
I could not reproduce adding an ETH address to the UI and submit. I would probably agree that it was done with a "manual" interaction with the contract. 

Still it might be helpful having an additional check also starting to add own error messages for the user to follow up better.
I've tried to modify a bit of text where I myself had a bit trouble understanding what is desired. Object to discussion.

**Comment by moonstash** [comment]
I am not opposed to additional checks! I also agree after looking at all the information it's possible / likely the end user bypassed our protections in some way. I can't be sure if accidental or intentional.

**Comment by moonstash** [comment]
@levackt any harm in merging this?

**Comment by levackt** [comment]
> @levackt any harm in merging this?

Looks good to me

**Comment by moonstash** [comment]
oh @Tosch110 there is a small merge conflict.

**Pull request merged**
